# Generated by Django 2.2.6 on 2019-10-31 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAmanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='course',
            name='isFull',
        ),
        migrations.AddField(
            model_name='course',
            name='dates',
            field=models.CharField(default='MTWRFS', max_length=6),
        ),
        migrations.AddField(
            model_name='course',
            name='endTime',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Start Time:'),
        ),
        migrations.AddField(
            model_name='course',
            name='startTime',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Start Time:'),
        ),
    ]
