# Generated by Django 2.2.6 on 2019-10-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='CS361', max_length=20),
        ),
    ]
